"""File-system helpers, cache utilities, and related abstractions."""
from __future__ import annotations

from .cache import CacheItem, CacheManager
from .file_manager import (
    FileManagerError,
    atomic_write,
    atomic_write_bytes,
    copy_dir,
    copy_file,
    delete_dir,
    delete_file,
    ensure_dir,
    list_files,
    move_dir,
    move_file,
    pick_file,
    read_bytes,
    read_json,
    read_lines,
    read_text,
    touch_file,
    write_bytes,
    write_json,
    write_lines,
    write_text,
)

__all__ = [
    "CacheItem",
    "CacheManager",
    "FileManagerError",
    "atomic_write",
    "atomic_write_bytes",
    "copy_dir",
    "copy_file",
    "delete_dir",
    "delete_file",
    "ensure_dir",
    "list_files",
    "move_dir",
    "move_file",
    "pick_file",
    "read_bytes",
    "read_json",
    "read_lines",
    "read_text",
    "touch_file",
    "write_bytes",
    "write_json",
    "write_lines",
    "write_text",
]
