"""Utility helpers and file management."""

from .helpers import (
    log,
    open_path,
    slugify,
    calc_hash,
    calc_hash_cached,
    calc_hashes,
    get_system_info,
    get_system_metrics,
)
from .vm import launch_vm_debug
from .file_manager import (
    read_text,
    write_text,
    pick_file,
    copy_file,
    move_file,
    delete_file,
    list_files,
    copy_dir,
    move_dir,
    delete_dir,
)
from .process_monitor import ProcessEntry, ProcessWatcher
from .network import (
    PortInfo,
    HTTPInfo,
    AutoScanInfo,
    get_mac_address,
    get_mac_vendor,
    _guess_os_from_ttl,
    _guess_device_type,
    _estimate_risk,
    TOP_PORTS,
    scan_ports,
    async_scan_ports,
    scan_port_list,
    async_scan_port_list,
    scan_top_ports,
    async_scan_top_ports,
    scan_targets_list,
    async_scan_targets_list,
    scan_targets,
    async_scan_targets,
    async_auto_scan,
    async_get_http_info,
    async_filter_active_hosts,
    detect_local_hosts,
    parse_port_range,
    parse_ports,
    ports_as_range,
    parse_hosts,
    clear_scan_cache,
    clear_host_cache,
)

from .ui import center_window

from . import file_manager

__all__ = [
    "log",
    "read_text",
    "write_text",
    "pick_file",
    "copy_file",
    "move_file",
    "delete_file",
    "list_files",
    "copy_dir",
    "move_dir",
    "delete_dir",
    "open_path",
    "slugify",
    "calc_hash",
    "calc_hash_cached",
    "calc_hashes",
    "get_system_info",
    "get_system_metrics",
    "launch_vm_debug",
    "scan_ports",
    "async_scan_ports",
    "scan_port_list",
    "async_scan_port_list",
    "scan_top_ports",
    "async_scan_top_ports",
    "scan_targets",
    "scan_targets_list",
    "async_scan_targets",
    "async_scan_targets_list",
    "async_auto_scan",
    "async_get_http_info",
    "AutoScanInfo",
    "HTTPInfo",
    "get_mac_address",
    "get_mac_vendor",
    "_guess_os_from_ttl",
    "_guess_device_type",
    "_estimate_risk",
    "async_filter_active_hosts",
    "detect_local_hosts",
    "parse_port_range",
    "parse_ports",
    "ports_as_range",
    "parse_hosts",
    "clear_scan_cache",
    "clear_host_cache",
    "TOP_PORTS",
    "PortInfo",
    "file_manager",
    "ProcessEntry",
    "ProcessWatcher",
    "center_window",
]
