"""Utility helpers and file management."""

import os

from .system_utils import (
    open_path,
    slugify,
    strip_ansi,
    get_system_info,
    get_system_metrics,
    run_with_spinner,
    console,
)
from .hash_utils import (
    calc_data_hash,
    calc_hash,
    calc_hash_cached,
    calc_hashes,
)
from .color_utils import (
    lighten_color,
    darken_color,
    adjust_color,
    hex_brightness,
)
from .rainbow import RainbowBorder, NeonPulseBorder
from .vm import launch_vm_debug
from .file_manager import (
    FileManagerError,
    read_text,
    write_text,
    read_lines,
    write_lines,
    read_bytes,
    write_bytes,
    read_json,
    write_json,
    atomic_write,
    atomic_write_bytes,
    ensure_dir,
    touch_file,
    pick_file,
    copy_file,
    move_file,
    delete_file,
    list_files,
    copy_dir,
    move_dir,
    delete_dir,
)
from .process_monitor import ProcessEntry, ProcessWatcher
from .process_cache import ProcessCache
from .network import (
    PortInfo,
    HTTPInfo,
    AutoScanInfo,
    get_mac_address,
    async_get_mac_address,
    get_mac_vendor,
    _guess_os_from_ttl,
    _guess_device_type,
    _estimate_risk,
    TOP_PORTS,
    scan_ports,
    async_scan_ports,
    scan_port_list,
    async_scan_port_list,
    scan_top_ports,
    async_scan_top_ports,
    scan_targets_list,
    async_scan_targets_list,
    scan_targets,
    async_scan_targets,
    async_auto_scan_iter,
    async_auto_scan,
    async_scan_hosts_iter,
    async_scan_hosts_detailed,
    async_get_http_info,
    async_collect_http_info,
    async_filter_active_hosts,
    async_detect_local_hosts,
    detect_local_hosts,
    detect_arp_hosts,
    async_get_hostname,
    auto_scan_info_to_dict,
    auto_scan_results_to_dict,
    clear_dns_cache,
    clear_local_host_cache,
    parse_port_range,
    parse_ports,
    ports_as_range,
    parse_hosts,
    clear_scan_cache,
    clear_host_cache,
    clear_http_cache,
    clear_ping_cache,
    clear_arp_cache,
)

if not os.environ.get("COOLBOX_LIGHTWEIGHT"):
    from .ui import center_window, get_screen_refresh_rate
else:  # pragma: no cover - testing without UI deps
    def center_window(*_a: object, **_k: object) -> None:
        pass
    def get_screen_refresh_rate(*_a: object, **_k: object) -> int:
        return 60
from .kill_utils import kill_process, kill_process_tree
from .win_console import (
    hide_console,
    hidden_creation_flags,
    hide_terminal,
    silence_stdio,
)
from .process_utils import (
    run_command,
    run_command_async,
    run_command_ex,
    run_command_async_ex,
    run_command_background,
)
from .scoring_engine import ScoringEngine, Tuning, tuning
from .security import (
    is_firewall_enabled,
    set_firewall_enabled,
    set_defender_enabled,
    set_defender_realtime,
    get_defender_status,
    is_defender_realtime_on,
    is_admin,
)
from .thread_manager import ThreadManager
from .gpu import benchmark_gpu_usage

from . import file_manager

__all__ = [
    "FileManagerError",
    "read_text",
    "write_text",
    "read_lines",
    "write_lines",
    "read_bytes",
    "write_bytes",
    "read_json",
    "write_json",
    "atomic_write",
    "atomic_write_bytes",
    "ensure_dir",
    "touch_file",
    "pick_file",
    "copy_file",
    "move_file",
    "delete_file",
    "list_files",
    "copy_dir",
    "move_dir",
    "delete_dir",
    "open_path",
    "slugify",
    "strip_ansi",
    "calc_data_hash",
    "calc_hash",
    "calc_hash_cached",
    "calc_hashes",
    "get_system_info",
    "get_system_metrics",
    "lighten_color",
    "darken_color",
    "adjust_color",
    "hex_brightness",
    "run_with_spinner",
    "console",
    "RainbowBorder",
    "NeonPulseBorder",
    "launch_vm_debug",
    "scan_ports",
    "async_scan_ports",
    "scan_port_list",
    "async_scan_port_list",
    "scan_top_ports",
    "async_scan_top_ports",
    "scan_targets",
    "scan_targets_list",
    "async_scan_targets",
    "async_scan_targets_list",
    "async_auto_scan_iter",
    "async_auto_scan",
    "async_scan_hosts_iter",
    "async_scan_hosts_detailed",
    "async_get_http_info",
    "AutoScanInfo",
    "HTTPInfo",
    "get_mac_address",
    "async_get_mac_address",
    "get_mac_vendor",
    "_guess_os_from_ttl",
    "_guess_device_type",
    "_estimate_risk",
    "async_filter_active_hosts",
    "async_detect_local_hosts",
    "detect_local_hosts",
    "detect_arp_hosts",
    "async_get_hostname",
    "auto_scan_info_to_dict",
    "auto_scan_results_to_dict",
    "clear_dns_cache",
    "clear_local_host_cache",
    "parse_port_range",
    "parse_ports",
    "ports_as_range",
    "parse_hosts",
    "clear_scan_cache",
    "clear_host_cache",
    "clear_http_cache",
    "clear_ping_cache",
    "clear_arp_cache",
    "async_collect_http_info",
    "TOP_PORTS",
    "PortInfo",
    "file_manager",
    "ProcessEntry",
    "ProcessWatcher",
    "ProcessCache",
    "center_window",
    "get_screen_refresh_rate",
    "kill_process",
    "kill_process_tree",
    "hide_console",
    "hide_terminal",
    "silence_stdio",
    "hidden_creation_flags",
    "run_command_async_ex",
    "run_command_ex",
    "run_command_async",
    "run_command",
    "run_command_background",
    "is_firewall_enabled",
    "set_firewall_enabled",
    "set_defender_enabled",
    "set_defender_realtime",
    "get_defender_status",
    "is_defender_realtime_on",
    "is_admin",
    "ScoringEngine",
    "Tuning",
    "tuning",
    "ThreadManager",
    "benchmark_gpu_usage",
]
