# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: toolbus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'toolbus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtoolbus.proto\x12\x0f\x63oolbox.toolbus\"\x94\x01\n\x06Header\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04tool\x18\x02 \x01(\t\x12\x37\n\x08metadata\x18\x03 \x03(\x0b\x32%.coolbox.toolbus.Header.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"I\n\rInvokeRequest\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.coolbox.toolbus.Header\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"q\n\x0eInvokeResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12+\n\x06status\x18\x02 \x01(\x0e\x32\x1b.coolbox.toolbus.StatusCode\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"I\n\rStreamRequest\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.coolbox.toolbus.Header\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\x85\x01\n\x0bStreamChunk\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x15\n\rend_of_stream\x18\x03 \x01(\x08\x12+\n\x06status\x18\x04 \x01(\x0e\x32\x1b.coolbox.toolbus.StatusCode\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"K\n\x10SubscribeRequest\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.coolbox.toolbus.Header\x12\x0e\n\x06topics\x18\x02 \x03(\t\"\xa4\x01\n\x05\x45vent\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x36\n\x08metadata\x18\x03 \x03(\x0b\x32$.coolbox.toolbus.Event.MetadataEntry\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"U\n\x03\x41\x63k\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12+\n\x06status\x18\x02 \x01(\x0e\x32\x1b.coolbox.toolbus.StatusCode\x12\r\n\x05\x65rror\x18\x03 \x01(\t*v\n\nStatusCode\x12\r\n\tSTATUS_OK\x10\x00\x12\x10\n\x0cSTATUS_ERROR\x10\x01\x12\x14\n\x10STATUS_NOT_FOUND\x10\x02\x12\x16\n\x12STATUS_UNAVAILABLE\x10\x03\x12\x19\n\x15STATUS_GUARD_REJECTED\x10\x04\x42\x15\n\x13\x63om.coolbox.toolbusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'toolbus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.coolbox.toolbus'
  _globals['_HEADER_METADATAENTRY']._loaded_options = None
  _globals['_HEADER_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EVENT_METADATAENTRY']._loaded_options = None
  _globals['_EVENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_STATUSCODE']._serialized_start=917
  _globals['_STATUSCODE']._serialized_end=1035
  _globals['_HEADER']._serialized_start=35
  _globals['_HEADER']._serialized_end=183
  _globals['_HEADER_METADATAENTRY']._serialized_start=136
  _globals['_HEADER_METADATAENTRY']._serialized_end=183
  _globals['_INVOKEREQUEST']._serialized_start=185
  _globals['_INVOKEREQUEST']._serialized_end=258
  _globals['_INVOKERESPONSE']._serialized_start=260
  _globals['_INVOKERESPONSE']._serialized_end=373
  _globals['_STREAMREQUEST']._serialized_start=375
  _globals['_STREAMREQUEST']._serialized_end=448
  _globals['_STREAMCHUNK']._serialized_start=451
  _globals['_STREAMCHUNK']._serialized_end=584
  _globals['_SUBSCRIBEREQUEST']._serialized_start=586
  _globals['_SUBSCRIBEREQUEST']._serialized_end=661
  _globals['_EVENT']._serialized_start=664
  _globals['_EVENT']._serialized_end=828
  _globals['_EVENT_METADATAENTRY']._serialized_start=136
  _globals['_EVENT_METADATAENTRY']._serialized_end=183
  _globals['_ACK']._serialized_start=830
  _globals['_ACK']._serialized_end=915
# @@protoc_insertion_point(module_scope)
